site_name: Sledge
site_url: !ENV READTHEDOCS_CANONICAL_URL
repo_url: https://github.com/arrowsv/sledge

theme:
  name: material
  logo: assets/icon.png
  favicon: assets/icon.png
  palette:
    scheme: slate
    primary: black
  font:
    text: Roboto
  features:
    - search.suggest
    - navigation.sections
    - navigation.footer
    - navigation.top
    - content.code.copy

markdown_extensions:
  - admonition
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: true
  - pymdownx.highlight
  - pymdownx.details
  - pymdownx.superfences 

validation:
  links:
    absolute_links: relative_to_docs
    
plugins:
  - search
  - awesome-nav
