[[enums]]
name = "event"

  [[enums.fields]]
  name = "player_do_frame"
  type = "integer"

  [[enums.fields]]
  name = "alert_level_changed"
  type = "integer"

  [[enums.fields]]
  name = "save_loaded"
  type = "integer"
  
  [[enums.fields]]
  name = "key_down"
  type = "integer"

  [[enums.fields]]
  name = "key_up"
  type = "integer"
  
  [[enums.fields]]
  name = "mouse_wheel"
  type = "integer"
  