[[namespaces]]
name = "sledge"

  [[namespaces.functions]]
  name = "log"

    [[namespaces.functions.params]]
    name = "message"
    type = "string"

  [[namespaces.functions]]
  name = "log_warn"

    [[namespaces.functions.params]]
    name = "message"
    type = "string"

  [[namespaces.functions]]
  name = "log_error"

    [[namespaces.functions.params]]
    name = "message"
    type = "string"

  [[namespaces.functions]]
  name = "register_window"

    [[namespaces.functions.params]]
    name = "title"
    type = "string"

    [[namespaces.functions.params]]
    name = "callback"
    type = "function"

    [[namespaces.functions.params]]
    name = "options"
    type = "table"
    optional = true
    
      [[namespaces.functions.params.fields]]
      name = "width"
      type = "number"
      optional = true

      [[namespaces.functions.params.fields]]
      name = "height"
      type = "number"
      optional = true

      [[namespaces.functions.params.fields]]
      name = "auto_resize"
      type = "boolean"
      description = "If `true`, the window will automatically resize to its contents, ignore any provided width or height, and remove the ability for users to manually resize it."
      optional = true

      [[namespaces.functions.params.fields]]
      name = "no_resize"
      type = "boolean"
      description = "If `true`, the window will remove the ability for users to manually resize it."
      optional = true

      [[namespaces.functions.params.fields]]
      name = "requires_gameplay"
      type = "boolean"
      description = "If `true`, the window will only draw its contents if the user is in gameplay. Recommended for panels that access objects only valid in gameplay, such as [`types.player`](types.player.md)."
      optional = true

  [[namespaces.functions]]
  name = "register_widget"

    [[namespaces.functions.params]]
    name = "title"
    type = "string"

    [[namespaces.functions.params]]
    name = "callback"
    type = "function"

    [[namespaces.functions.params]]
    name = "options"
    type = "table"
    optional = true

      [[namespaces.functions.params.fields]]
      name = "requires_gameplay"
      type = "boolean"
      description = "If `true`, the widget will only draw its contents if the user is in gameplay. Recommended for panels that access objects only valid in gameplay, such as [`types.player`](types.player.md)."
      optional = true

  [[namespaces.functions]]
  name = "register_event"

    [[namespaces.functions.params]]
    name = "event"
    type = "enums.event"

    [[namespaces.functions.params]]
    name = "callback"
    type = "function"

  [[namespaces.functions]]
  name = "register_file"

    [[namespaces.functions.params]]
    name = "path"
    type = "string"

  [[namespaces.functions]]
  name = "register_packfile"

    [[namespaces.functions.params]]
    name = "path"
    type = "string"

  [[namespaces.functions]]
  name = "register_xml_edit"

    [[namespaces.functions.params]]
    name = "name"
    type = "string"

    [[namespaces.functions.params]]
    name = "callback"
    type = "function"