[[events]]
name = "key_down"
description = "This event is triggered a key is pressed."

    [[events.data]]
    name = "key"
    type = "defines.key"

    [[events.data]]
    name = "shift_down"
    type = "boolean"

    [[events.data]]
    name = "control_down"
    type = "boolean"

    [[events.data]]
    name = "alt_down"
    type = "boolean"