mod:register_event(defines.event.parse_xml, function(data)
    local table = data.document:get("root"):get("Table")

    local nano_rifle = table:get_from_path("Weapon[Name='nano_rifle']")
    nano_rifle:get("Trigger_Type"):set("automatic")
    nano_rifle:get("Magazine_Size"):set("60")
    nano_rifle:get("Max_Rounds"):set("250")
    nano_rifle:get("Range_Max"):set("150")
    nano_rifle:get("Range_Red"):set("250")
    nano_rifle:get("Default_Refire_Delay"):set("100")
    nano_rifle:get("Ammo_Box_Restock"):set("150")
    nano_rifle:get("Num_Magazines"):set("6")
    nano_rifle:get("Reload_Delay"):set("200")
end, { filter = "weapons.xtbl" })
