id = "arrows.cheat_window"
name = "Cheat Window"
authors = ["arrows"]
description = """Adds a cheat window that exposes various variables for viewing/editing:

- Statistics
- Team
- Flags
- Time of day
- Alert level
"""
version = "1.0.0"
sledge_version = "^0.1.0"
