[[types]]
name = "matrix"

  [[types.fields]]
  name = "right"
  type = "types.vector"

  [[types.fields]]
  name = "up"
  type = "types.vector"

  [[types.fields]]
  name = "forward"
  type = "types.vector"