preserve_directory_names: true

nav:
  - index.md
  - changelog.md
  - Guides:

    - Players:
      - Installing Sledge: guides/players/installing-sledge.md
      - Using Sledge: guides/players/using-sledge.md
      - Updating Sledge: guides/players/updating.md
      - Managing your mods: guides/players/managing-mods.md

    - Developers:

      - Creating your mod: guides/developers/mod.md
      - Writing your script: guides/developers/script.md

      - Editing files:
        - Overview: guides/developers/editing-files/index.md
        - Editing XML files: guides/developers/editing-files/editing-xml-files.md
        - Overriding files: guides/developers/editing-files/overriding-files.md
        - Converting legacy mods: guides/developers/editing-files/legacy-mods.md

      - Creating panels:
        - Overview: guides/developers/creating-panels/index.md
        - Drawing elements: guides/developers/creating-panels/drawing-elements.md
        - Preventing script errors: guides/developers/creating-panels/script-errors.md
  
      - Testing your mod: guides/developers/testing.md
      - Publishing your mod: guides/developers/publishing.md

  - API:
    - Overview: "api/overview.md"
    - Changelog: "api/changelog.md"
    - Metadata: "api/metadata.md"
    
    - Lua:
      - Namespaces:
        - "api/lua/namespaces.*"

      - Types:
        - "api/lua/types.*"

      - Enums:
        - "api/lua/enums.*"

      - Events:
        - "api/lua/events.*"