#pragma once

#include <filesystem>
#include <string>
#include <windows.h>

namespace utils::os {
void show_message_info(const std::string& message);
void show_message_error(const std::string& message);
std::string read_file_to_string(const std::string& path);
std::filesystem::path get_module_directory(HMODULE h_module);
std::string open_file_dialog(const char* filter, const char* title = "Open");
std::optional<std::filesystem::path> open_folder_dialog();

enum class key {
    none = 0,
    mouse_left = VK_LBUTTON,
    mouse_right = VK_RBUTTON,
    mouse_middle = VK_MBUTTON,
    backspace = VK_BACK,
    enter = VK_RETURN,
    tab = VK_TAB,
    space = VK_SPACE,
    caps_lock = VK_CAPITAL,
    nav_insert = VK_INSERT,
    nav_delete = VK_DELETE,
    nav_end = VK_END,
    nav_home = VK_HOME,
    nav_page_up = VK_PRIOR,
    nav_page_down = VK_NEXT,
    arrow_left = VK_LEFT,
    arrow_up = VK_UP,
    arrow_right = VK_RIGHT,
    arrow_down = VK_DOWN,
    shift = VK_SHIFT,
    shift_left = 0xA0,
    shift_right = 0xA1,
    control = VK_CONTROL,
    control_left = 0xA2,
    control_right = 0xA3,
    alt = VK_MENU,
    alt_left = VK_LMENU,
    alt_right = VK_RMENU,
    semicolon = VK_OEM_1,
    plus = VK_OEM_PLUS,
    comma = VK_OEM_COMMA,
    period = VK_OEM_PERIOD,
    minus = VK_OEM_MINUS,
    forward_slash = VK_OEM_2,
    tilde = VK_OEM_3,
    f1 = VK_F1,
    f2 = VK_F2,
    f3 = VK_F3,
    f4 = VK_F4,
    f5 = VK_F5,
    f6 = VK_F6,
    f7 = VK_F7,
    f8 = VK_F8,
    f9 = VK_F9,
    f10 = VK_F10,
    f11 = VK_F11,
    f12 = VK_F12,
    f13 = VK_F13,
    f14 = VK_F14,
    f15 = VK_F15,
    f16 = VK_F16,
    f17 = VK_F17,
    f18 = VK_F18,
    f19 = VK_F19,
    f20 = VK_F20,
    f21 = VK_F21,
    f22 = VK_F22,
    f23 = VK_F23,
    f24 = VK_F24,
    numpad_0 = VK_NUMPAD0,
    numpad_1 = VK_NUMPAD1,
    numpad_2 = VK_NUMPAD2,
    numpad_3 = VK_NUMPAD3,
    numpad_4 = VK_NUMPAD4,
    numpad_5 = VK_NUMPAD5,
    numpad_6 = VK_NUMPAD6,
    numpad_7 = VK_NUMPAD7,
    numpad_8 = VK_NUMPAD8,
    numpad_9 = VK_NUMPAD9,
    numpad_multiply = VK_MULTIPLY,
    numpad_add = VK_ADD,
    numpad_subtract = VK_SUBTRACT,
    numpad_separator = VK_SEPARATOR,
    numpad_decimal = VK_DECIMAL,
    numpad_divide = VK_DIVIDE,
    num_0 = 0x30,
    num_1 = 0x31,
    num_2 = 0x32,
    num_3 = 0x33,
    num_4 = 0x34,
    num_5 = 0x35,
    num_6 = 0x36,
    num_7 = 0x37,
    num_8 = 0x38,
    num_9 = 0x39,
    a = 0x41,
    b = 0x42,
    c = 0x43,
    d = 0x44,
    e = 0x45,
    f = 0x46,
    g = 0x47,
    h = 0x48,
    i = 0x49,
    j = 0x4A,
    k = 0x4B,
    l = 0x4C,
    m = 0x4D,
    n = 0x4E,
    o = 0x4F,
    p = 0x50,
    q = 0x51,
    r = 0x52,
    s = 0x53,
    t = 0x54,
    u = 0x55,
    v = 0x56,
    w = 0x57,
    x = 0x58,
    y = 0x59,
    z = 0x5A
};

std::string key_to_string(key key);
key key_from_string(const std::string& string);

} // namespace utils::os
