[[types]]
name = "player"
inherits = "types.human"

  [[types.properties]]
  name = "jetpack_fuel_percent"
  type = "number"

  [[types.properties]]
  name = "salvage"
  type = "integer"

  [[types.properties]]
  name = "mining_count"
  type = "integer"

  [[types.properties]]
  name = "supply_crate_count"
  type = "integer"